### ISSUE TITLE
reader.h throws an error

### ISSUE THREAD

**Issue by armedturret** [open-source-parsers/jsoncpp#686]
Umm, this thing happens for some reason.
I use visual studio and included json.h and value.h
```cpp
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): error C4996: 'Json::Reader::Char': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(37): note: see declaration of 'Json::Reader::Char'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(181): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(182): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(189): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(196): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(212): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(213): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(216): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(217): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(219): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(226): error C4996: 'Json::Reader::Char': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(37): note: see declaration of 'Json::Reader::Char'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(228): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(229): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(230): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(233): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(234): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(237): error C4996: 'Json::Reader::Nodes': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(236): note: see declaration of 'Json::Reader::Nodes'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(238): error C4996: 'Json::Reader::Errors': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(192): note: see declaration of 'Json::Reader::Errors'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(240): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(241): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(242): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(243): error C4996: 'Json::Reader::Location': Use CharReader and CharReaderBuilder instead
1>c:\users\rjwhi\source\repos\infinidungeon\deps\include\json\reader.h(38): note: see declaration of 'Json::Reader::Location'
```

**Comment by cdunn2001** [comment]
I think the tip of `master` suppresses those warnings in VisualStudio.

**Comment by frankyugit** [comment]
Hi, guys, I have met similar problem with VS2015 on windows 7
Just an simple example, but still can't pass compiling, with the error about "Json::Reader::Location': Use CharReader and CharReaderBuilder instead"
Any solution for this?
Ans what's the tip in master, @cdunn2001

**Comment by cdunn2001** [comment]
No ideas. We would need your help debugging this.

Note that we do test VS 2013 and 2015 on AppVeyor. Maybe you are using amalgamate.py, which we do *not* test.

**Comment by Wasdns** [comment]
Hi, all. The same error occurred when I compiling my [program](https://github.com/Wasdns/Deputy/blob/master/Project/jsonHandler.cpp#L17) on VS2015. However, my program works fine on the linux environment(Ubuntu14.04). Any ideas to resolve this?
@cdunn2001 BTW, I don't understand "the tip of `master`" clearly. Could you explain it? Thanks a lot.

**Comment by cdunn2001** [comment]
@Wasdns, "tip of `master`" refers to the most recent git-commit on the `master` branch. You might be using a tagged release, and I don't think the most recent release is quite the latest commit today.

But look at `appveyor.yml`. We use that to build in AppVeyor. We continually test both VS2013 and VS2015. If there is something else we need to test, or some better way to do it, please help us!

**Comment by Wasdns** [comment]
@cdunn2001 Okey. Thanks a lot!

**Comment by armedturret** [comment]
I used cmake and was able to remove the deprecation from reader.h. I was operating in vs 2017 and it works fine now.

**Comment by BeErikk** [comment]
It is the `-sdl` compiler switch that turn some warnings to errors, ie C4996  => /we4996

see MSDN [/sdl (Enable Additional Security Checks)](https://docs.microsoft.com/en-gb/cpp/build/reference/sdl-enable-additional-security-checks)

You need some option to disable the warning when building the library.

**Comment by jbmonroe** [comment]
That may be--but my complaint with it is that the error text seems to be

a) Not present in the source (messaged via #pragma, isn't it), and
b) Not relevant--I _am_ using CharReader and CharReaderBuilder, so why is it warning me to use them?

**Comment by cdunn2001** [comment]
@jbmonroe , if you figure out a way to suppress these properly, please post. That could be helpful to others too.

**Comment by jbmonroe** [comment]
I tried suppressing the messages via #pragma in stdafx.h and even that didn't work.  I might try it via command-line next--and if I figure it out, I'll definitely publish here.  As @BeErikk points out it's an SDL warning, and I think it's happening because while I'm using the recommended APIs, but the code under the hood isn't (and shouldn't have to).  I think it's an example of Too-Helpful Compiler Syndrome.  I have an idea, though....

**Comment by jbmonroe** [comment]
Well, there's your problem right there:

```
class JSONCPP_DEPRECATED("Use CharReader and CharReaderBuilder instead") JSON_API Reader {
.
.
.
};
```
```
#  if _MSC_VER >= 1500 // MSVC 2008
    /// Indicates that the following function is deprecated.
#    define JSONCPP_DEPRECATED(message) __declspec(deprecated(message))
#  endif
```

Rather than forcing a warning during the inclusion of a class that we shouldn't be using, one could just not include the class by precompile tests around it.  (At the risk of breaking older code using the library--but them's the breaks.  One should always read the release notes, am I right?)

The immediate solution is to bracket the Reader class declaration with #pragma warning disable/default for 4996, but that's overkill since--unless I'm badly mistaken in understanding the warning--we don't need the Reader class for any Visual Studio version past VS2005.

**Comment by cdunn2001** [comment]
I'd be fine with un-deprecating. Just deprecate in a comment.

Someone people use this old class. But it's very difficult to maintain, for a variety of reasons. C++ coders just don't understand dependency-injection.

**Comment by jbmonroe** [comment]
> C++ coders just don't understand dependency-injection.

https://www.youtube.com/watch?v=4XNr-BQgpd0

(Just kidding.  I work with a two-decade-old C++ framework that's built on dependency injection, but it's definitely looking a bit lonesome in the Big World o' Code.  Using dependency injection eliminates a lot of issues in multi-threaded programming in C++.)

For the build I have I can leave it as-is or deprecate via comments.  The newer classes are far more tidy.  So, as a shout-out to those still using Reader: modern up, already! :)

**Comment by cdunn2001** [comment]
Ha! I'm always glad to find a C++ coder who "gets it".
